/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author akatsuki
 */
import java.sql.*;
import java.util.*;
import javax.swing.*;

public class Main_login_frame extends javax.swing.JFrame {
    
    public static String currUser = ""; 

    
    

    /**
     * Creates new form Main_login_frame
     */
    public Main_login_frame() {
        initComponents();
    }
//    Keep current user class in the main page and create a place holder
    
//    Tree maps are created using class variables. The keyset is a string value and it is case insensitive
    public static  Map<String, Instructor> instructor_hash = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
    public static Map<String, Student> student_hash = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
    public static Map<String, Admin> admin_hash = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setToolTipText("");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, 30));
        jTextField1.getAccessibleContext().setAccessibleName("userText");

        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 180, 30));
        jPasswordField1.getAccessibleContext().setAccessibleName("userPass");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Instructor", "Student", "Admin" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 180, 30));
        jComboBox1.getAccessibleContext().setAccessibleName("selection");

        jButton2.setText("login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleName("User_label");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("User Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buildings-wabash-and-AUD-from-south-evening.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String inputText = jTextField1.getText().toString().trim().toLowerCase();
        int inputPass = Integer.parseInt(jPasswordField1.getText().trim());
        if(jComboBox1.getSelectedItem() == "Admin"){
            System.out.println("Admin found");
            for(Map.Entry<String, Admin> entry: admin_hash.entrySet()){
               if((inputText.equalsIgnoreCase(entry.getKey()) && (inputPass == (entry.getValue().getPass())))){

//                      Admin email and password match proceed to next page
                    System.out.println("Match found " + entry.getKey());
//                    set current user as admin and change current user to true
                    currUser = inputText;
                    entry.getValue().setCurrUser(true);
                    dispose();
                    JOptionPane.showMessageDialog(null, "Login Successfull");
                }else{
                   JOptionPane.showMessageDialog(null, "Password does not match please try again");
                   
                }
            }
        }else if(jComboBox1.getSelectedItem() == "Instructor"){
            for(Map.Entry<String, Instructor> entry: instructor_hash.entrySet()){
                if((inputText.equalsIgnoreCase(entry.getKey()) && (inputPass == (entry.getValue().getPass())))){
//                        The instructor email and password match proceed to next page
                    currUser = inputText;
                    entry.getValue().setCurrUser(true);
                    dispose();
                    Instructor_frame newInst = new Instructor_frame();
                    newInst.setVisible(true);
                    
                }else{
                   JOptionPane.showMessageDialog(null, "Password or email does not match please try again");
                }
            }    
        }else if(jComboBox1.getSelectedItem() == "Student"){
            System.out.println("Student found");
            for(Map.Entry<String, Student> entry: student_hash.entrySet()){
                if((inputText.equalsIgnoreCase(entry.getKey()) && (inputPass == (entry.getValue().getPass())))){
//                        The student email and password match proceed to next page
                    currUser = inputText;
                    entry.getValue().setCurrUser(true);
                    dispose();
                }else{
                   JOptionPane.showMessageDialog(null, "Password or email does not match please try again");
                }
            }
        }else{
                JOptionPane.showMessageDialog(null, "Password or email does not match please try again");
        }  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
//        Creating admin for test
        Admin newAdmin = new Admin();
        newAdmin.setPass(123);
        newAdmin.setfName("admin");
        admin_hash.put("admin@mail", newAdmin);
        System.out.println("admin added");
        
//        Creating instructor for test
        Instructor newInst = new Instructor();
        newInst.setfName("Instructor");
        newInst.setPass(123);
        instructor_hash.put("inst@mail", newInst);
        System.out.println("instructor");
        
//        Creating student for test
        Student newStu = new Student();
        newStu.setfName("student");
        newStu.setPass(123);
        student_hash.put("student@mail", newStu);
        System.out.println("student added");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_login_frame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
}
