
import java.util.Map;
import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author akatsuki
 */
public class StudentFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bButton = new javax.swing.JButton();
        showGrade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bButton.setText("Close");
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });

        showGrade.setText("Show My Grades");
        showGrade.setToolTipText("");
        showGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(bButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showGrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(showGrade)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(bButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGradeActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)new DefaultTableModel(new Object[]{"Course Namel", "Quiz Ave", "Final Grade", "GPA"},0);
        System.out.println("Before search");
        for(Map.Entry<String,Student> entry: Main_login_frame.student_hash.entrySet()){
            System.out.println("Searching student");
            if(entry.getValue().isCurrUser()){
                Map <String, Student.Course> stCourse = entry.getValue().getCourse();
                
                for(Map.Entry<String,Student.Course> courseEntry: stCourse.entrySet()){
                    String courseName = courseEntry.getKey();
                    int stQuizAve = courseEntry.getValue().getQuizAve();
                    int stFinal = courseEntry.getValue().getFinalExam();
                    double stGpa = courseEntry.getValue().getGPA();
                    model.addRow(new Object[]{courseName, stQuizAve, stFinal,stGpa});
                }
            }
        }
        jTable1.setModel(model);
    }//GEN-LAST:event_showGradeActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        Student testStudent = new Student();
        testStudent.setCurrUser(true);
        String cst = "CST";
        Student.Course stCourse = testStudent.new Course();
        stCourse.setFinalExam(95);
        stCourse.setQuizAve(45);
        stCourse.setGPA(3.5);
        
        System.out.println("Student created");
        testStudent.addCourse(cst, stCourse);
        Main_login_frame.student_hash.put("bob@,=mail", testStudent);
        
        Student testStudent2 = new Student();
        testStudent2.setCurrUser(true);
        String cst2 = "CST";
        Student.Course stCourse2 = testStudent2.new Course();
        stCourse2.setFinalExam(70);
        stCourse2.setQuizAve(76);
        stCourse2.setGPA(3.4);
        

        
        System.out.println("Student created");
        testStudent.addCourse(cst2, stCourse);
        Main_login_frame.student_hash.put("bob2@,=mail", testStudent2);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton showGrade;
    // End of variables declaration//GEN-END:variables
}
